app = "abjadi-api"
primary_region = "fra"

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "3500"

[http_service]
  internal_port = 3500
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 40

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
